name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npx ci
      - name: Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release
      # - name: Get Tags
      #   run: git fetch origin +refs/tags/*:refs/tags/*
      # echo the tag number out
      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: 'Update version'
        id: package-json
        uses: actions/checkout@v2
        uses: johnnybenson/package-json-versioned-action@v1.0.5
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "has-updated -- ${{ steps.package-json.outputs.has-updated }}"
      - run: echo "previous-version -- ${{ steps.package-json.outputs.previous-version }}"
      - run: echo "version -- ${{ steps.package-json.outputs.version }}"          
      # - name: 'Output previous tag'
      #   run: |
      #     echo: ${{ steps.previoustag.outputs.tag }}
      # - name: 'package.json info'
      #   id: info
      #   uses: jaywcjlove/github-action-package@main

      # - run: echo "name - ${{ steps.info.outputs.name }}"
      # - run: echo "version - ${{ steps.info.outputs.version }}"
      # - run: echo "description - ${{ steps.info.outputs.description }}"
      # - run: echo "author - ${{ steps.info.outputs.author }}"

      # - name: 'update version with previous tag'
      #   id: info
      #   uses: jaywcjlove/github-action-package@main
      #   with:
      #     rename: '@jaywcjlove/github-action-package-test'

      # - run: echo "name - ${{ steps.info.outputs.name }}"
      # - run: echo "version - ${{ steps.previoustag.outputs.tag }}"
      # - run: echo "description - ${{ steps.info.outputs.description }}"
      # - run: echo "author - ${{ steps.info.outputs.author }}"

      
